import { FieldInputs } from '../../utils/types/dataTypes';

const inputs: Record<string, FieldInputs[]> = {
    data: [
        {
            name: 'email',
            label: 'Почта',
            type: 'email',
            required: 'true',
            id: 'email',
            value: '',
            validate_rule: 'email',
        },
        {
            name: 'login',
            label: 'Логин',
            type: 'text',
            required: 'true',
            id: 'login',
            value: '',
            validate_rule: 'login',
        },
        {
            name: 'first_name',
            label: 'Имя',
            type: 'text',
            required: 'true',
            id: 'first_name',
            value: '',
            validate_rule: 'name',
        },
        {
            name: 'second_name',
            label: 'Фамилия',
            type: 'text',
            required: 'true',
            id: 'second_name',
            value: '',
            validate_rule: 'name',
        },
        {
            name: 'display_name',
            label: 'Имя в чате',
            type: 'text',
            required: 'true',
            id: 'display_name',
            value: '',
            validate_rule: 'name',
        },
        {
            name: 'phone',
            label: 'Телефон',
            type: 'text',
            required: 'true',
            id: 'phone',
            value: '',
            validate_rule: 'phone',
        },
    ],
    password: [
        {
            name: 'oldPassword',
            label: 'Старый пароль',
            type: 'password',
            required: 'true',
            id: 'oldPassword',
            value: '',
            validate_rule: 'password',
        },
        {
            name: 'newPassword',
            label: 'Новый пароль',
            type: 'password',
            required: 'true',
            id: 'newPassword',
            value: '',
            validate_rule: 'password',
        },
        {
            name: 'newPassword-repeat',
            label: 'Повторите новый пароль',
            type: 'password',
            required: 'true',
            id: 'newPassword-repeat',
            value: '',
            validate_rule: 'repeater',
            repeater_name: 'newPassword',
        },
    ],
};

export default inputs;
